Use require instead of import in DataUtil.spec.js
i.e. CommonJS modules instead of ES6 modules.

This fixes a weird issue where tests wouldn't run *in some
environments*.

The weird thing is that they would work on the exact same node and yarn
versions on a in a different environment.

```
olov@L19006:~/kod/lxlviewer/vue-client$ yarn test:unit
yarn run v1.22.19
$ vue-cli-service test:unit
 FAIL  tests/unit/DataUtil.spec.js
  ● Test suite failed to run

    /home/olov/kod/lxlviewer/vue-client/tests/unit/DataUtil.spec.js:2
    import * as DataUtil from '@/utils/data';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.848s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

olov@L19006:~/kod/lxlviewer/vue-client$ node --version
v14.21.3
olov@L19006:~/kod/lxlviewer/vue-client$ yarn --version
1.22.19
```